[package]
name = "rnes"
version = "0.1.0"
authors = ["Brian Schlenker <bschlenk@umich.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
lazy_static = "1.4.0"
